---
title: Airbnb EDA (cleaning, frequency distribution, box plots, colleration matrix,
  scatterplots)
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
```


```{r}
airbnb_palette <- c("#FF5A5F", "#00A699", "#767676", "#484848", "#FFB400")
```


```{r}
main_uncleaned_data <- read_csv("airbnb1.csv")

head(main_uncleaned_data)

summary(main_uncleaned_data)

glimpse(main_uncleaned_data)
```

```{r}
# Calculate the percentage of missing data for each column
missing_data <- main_uncleaned_data %>%
  summarise(across(everything(), ~ mean(is.na(.)) * 100)) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Missing_Percentage")

# Plot the missing data percentage
ggplot(missing_data, aes(x = reorder(Variable, -Missing_Percentage), y = Missing_Percentage)) +
  geom_bar(stat = "identity", fill = "#Ffb400") + 
  labs(title = "Percentage of Missing Data by Column", x = "Variable", y = "Missing Percentage (%)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45)) +
  coord_flip()
  
```



```{r}
which(is.na(main_uncleaned_data))

col_missing <- colSums(is.na(main_uncleaned_data))

col_missing

dropped_na <- main_uncleaned_data %>% drop_na()

which(is.na(dropped_na)) # just checking if the cleaning worked or not

Q1 <- quantile(dropped_na$bedrooms, 0.25, na.rm = TRUE)
Q3 <- quantile(dropped_na$bedrooms, 0.75, na.rm = TRUE)
IQR <- Q3 - Q1

cleaned_airbnb_data <- dropped_na %>%
  filter(bedrooms >= (Q1 - 1.5 * IQR) & bedrooms <= (Q3 + 1.5 * IQR))

glimpse(cleaned_airbnb_data)

```

```{r}
numeric_vars <- c("bathrooms", "bedrooms", "beds", "amenities_count", "minimum_nights", "maximum_nights", "number_of_reviews", "review_scores_rating", "price","availability_30","availability_60","availability_90","availability_365")

categorical_vars <- c("property_type", "room_type", "cancellation_policy", "host_identity_verifed","instant_bookable")
```


```{r}
par(mfrow = c(2, 4)) # Set up plotting layout

# Create a histogram for each variable
lapply(numeric_vars, function(var) {
  hist(dropped_na[[var]], 
       main = paste(var), 
       xlab = var, 
       col = "#FFB400", 
       border = "white"
       )
})
```

```{r}
par(mfrow = c(2, 4)) # 2 rows, 4 columns

# Create a boxplot for each variable
lapply(numeric_vars, function(var) {
  boxplot(dropped_na[[var]], 
          main = paste(var), 
          ylab = var, 
          col = "#00A699")
})
```

There are negative price outliers, so we'll filter that out
```{r}
# removing negative price values

cleaned_airbnb_data <- cleaned_airbnb_data %>%
  filter(price > 0)
```


```{r}
par(mfrow = c(2, 4)) # Set up plotting layout

# Create a histogram for each variable
lapply(numeric_vars, function(var) {
  hist(cleaned_airbnb_data[[var]], 
       main = paste(var), 
       xlab = var, 
       col = "#FFB400", 
       border = "white"
       )
})
```



```{r}
par(mfrow = c(2, 4)) # 2 rows, 4 columns

# Create a boxplot for each variable
lapply(numeric_vars, function(var) {
  boxplot(cleaned_airbnb_data[[var]], 
          main = paste(var), 
          ylab = var, 
          col = "#00A699")
})
```

```{r}
# Set up margins to accommodate rotated labels
par(mfrow=c(1, length(categorical_vars)), mar=c(6, 5, 3, 2))

# Create the bar plots with rotated labels
for (i in 1:length(categorical_vars)) {
  counts <- table(cleaned_airbnb_data[[categorical_vars[i]]])
  if (length(counts) == 0 || all(counts == 0)) {
    next
  }
  barplot(counts, main=categorical_vars[i], col='#ff5a5f', border='black', ylim=c(0, max(counts) + 10), las = 2)
}
```


```{r}
library(corrplot)

selected_df_for_modelling <- select(cleaned_airbnb_data, -latitude, -longitude, -cancellation_policy, -property_type, -room_type)

correlation_matrix <- cor(selected_df_for_modelling)

# Draw correlation heatmap
corrplot(correlation_matrix, 
         method = "circle",                # Use circles to represent correlations
         type = "full",                   # Display only upper triangle
         tl.col = "darkblue",              # Set font color to dark blue
         tl.srt = 45,                      # Rotate labels for better readability
         tl.cex = 0.8,                     # Adjust font size of labels
         cl.cex = 0.8,                     # Adjust font size of color legend
         pch.cex = 1.2)                 # Set size for the correlation coefficient numbers
```


```{r}
library(corrplot)

selected_df_for_modelling <- select(dropped_na, -latitude, -longitude, -cancellation_policy, -property_type, -room_type)

correlation_matrix <- cor(selected_df_for_modelling)

# Draw correlation heatmap
corrplot(correlation_matrix, 
         method = "circle",                # Use circles to represent correlations
         type = "full",                   # Display only upper triangle
         tl.col = "darkblue",              # Set font color to dark blue
         tl.srt = 45,                      # Rotate labels for better readability
         tl.cex = 0.8,                     # Adjust font size of labels
         cl.cex = 0.8,                     # Adjust font size of color legend
         pch.cex = 1.2)                 # Set size for the correlation coefficient numbers
```


```{r}
price_col_vars <- c("accommodates", "bathrooms", "bedrooms", "beds", "amenities_count")

# Check the class of each variable in numeric_vars
sapply(cleaned_airbnb_data [, price_col_vars], class)
cleaned_airbnb_data[, price_col_vars] <- lapply(cleaned_airbnb_data[, price_col_vars], as.numeric)

for (var in price_col_vars) {
  plot(
    as.numeric(cleaned_airbnb_data[[var]]), 
    as.numeric(cleaned_airbnb_data$price), 
    main = paste("Relationship between", var, "and Price"), 
    xlab = var, 
    ylab = "Price", 
    col = "#00A699", 
    pch = 19
  )
}
```

```{r}
library(ggplot2)

# Scatter plot with regression line
ggplot(cleaned_airbnb_data, aes(x = amenities_count , y = price)) +
  geom_point(color = "#00A699", alpha = 0.6) +
  geom_smooth(method = "lm", color = "#FF5A5F") +
  labs(title = "Price vs Number of Amenities", x = "Number of Amenities", y = "Price") +
  theme_minimal()

```

```{r}
# Scatter plot with regression line
ggplot(cleaned_airbnb_data, aes(x = number_of_reviews , y = price)) +
  geom_point(color = "#00A699", alpha = 0.6) +
  geom_smooth(method = "lm", color = "#FF5A5F") +
  labs(title = "Price vs Number of Reviews", x = "Number of Reviews", y = "Price") +
  theme_minimal()
```

```{r}
ggplot(cleaned_airbnb_data, aes(x = bedrooms, y = beds)) +
  geom_area(color = "#ffb400", fill = "#ffb400") +
  labs(title = "Area Chart for Beds and Bedrooms",
       x = "Bedrooms",
       y = "Beds") +
  theme_minimal()
```

```{r}
# Density plot of price by room type
ggplot(cleaned_airbnb_data, aes(x = price, fill = room_type,)) +
  geom_density(alpha = 0.5) +
  labs(title = "Price Density by Room Type", x = "Price", y = "Density") +
  theme_minimal()

```

```{r}
world_map <- map_data("state")

ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = "white") + 
  geom_point(data = cleaned_airbnb_data, aes(x = longitude, y = latitude, size = review_scores_rating, color = price))
```

```{r}
ggplot(cleaned_airbnb_data, aes(x = room_type, fill = factor(review_scores_rating))) +
  geom_bar(position = "fill") +
  labs(
    title = "Distribution of Review Score Rating by Room Type",
    x = "Room Type",
    y = "Count",
    fill = "Review Score Rating"
  ) +
  scale_fill_manual(values = airbnb_palette) +
  theme_minimal() 
```

```{r}
ggplot(cleaned_airbnb_data, aes(x = cancellation_policy , fill = factor(review_scores_rating))) +
  geom_bar(position = "fill") +
  labs(
    title = "Distribution of Review Score Rating by Cancellation Policy",
    x = "Cancellation Policy",
    y = "Count",
    fill = "Review Score Rating"
  ) +
  scale_fill_manual(values = airbnb_palette) +
  theme_minimal() 
```


```{r}
# Create the plot
ggplot(data = cleaned_airbnb_data, mapping = aes(x = amenities_count, y = price, color = room_type)) + 
  geom_point(size = 2) + 
  geom_smooth(mapping = aes(color = room_type), se = FALSE) + 
  scale_color_manual(values = c("Entire home/apt" = "#FF5A5F", 
                                "Private room" = "#00A699", 
                                "Shared room" = "#ffb400")) +
  theme_minimal() +
  labs(title = "Price vs. Amenities Count by Room Type",
       x = "Amenities Count",
       y = "Price",
       color = "Room Type")
```

```{r}
# Boxplot for Price by Property Type
ggplot(cleaned_airbnb_data, aes(x = property_type, y = price)) +
  geom_boxplot(fill = "#ffb400", color = "black") +
  labs(title = "Price by Property Type", x = "Property Type", y = "Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Boxplot for Price by Room Type
ggplot(cleaned_airbnb_data, aes(x = room_type, y = price)) +
  geom_boxplot(fill = "#ffb400", color = "black") +
  labs(title = "Price by Room Type", x = "Room Type", y = "Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
# Boxplot for host identity and review rating
ggplot(cleaned_airbnb_data, aes(x = factor(host_identity_verified), y = review_scores_rating)) +
  geom_boxplot(fill = "#ff5a5f", color = "black") +
  labs(title = "Rating by Host Veification", x = "Host Verification Status", y = "Rating") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
# Boxplot for host identity and price
ggplot(cleaned_airbnb_data, aes(x = factor(host_identity_verified), y = price)) +
  geom_boxplot(fill = "#ff5a5f", color = "black") +
  labs(title = "Price by Host Veification", x = "Host Verification Status", y = "Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(data = cleaned_airbnb_data, aes(x = property_type, y = availability_365)) +
  geom_boxplot(fill = "#00a699", color = "black") +
  labs(title = "Availability by Property Type", x = "Property Type", y = "Availability for next year") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(data = cleaned_airbnb_data, aes(x = property_type, y = availability_30)) +
  geom_boxplot(fill = "#00a699", color = "black") +
  labs(title = "Availability by Property Type", x = "Property Type", y = "Availability for next month") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
